providers = ["php", "node"]

[variables]
PHP_VERSION = "8.2"
APP_NAME = "DACE UNERG POSTGRADO"
APP_ENV = "production"
APP_DEBUG = "false"
APP_KEY = "base64:Gv0sGAfgv+zGVuH+ajk0PDpHp7SXVke50GTG3JWUNv0="
APP_LOCALE = "es"
APP_FALLBACK_LOCALE = "es"
DB_CONNECTION = "sqlite"
DB_DATABASE = "/app/database/database.sqlite"
SESSION_DRIVER = "database"
CACHE_STORE = "database"
QUEUE_CONNECTION = "database"
LOG_CHANNEL = "stderr"
VITE_APP_NAME = "${APP_NAME}"

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader --no-interaction",
  "npm ci --only=production",
  "npm run build",
  "mkdir -p database",
  "touch database/database.sqlite",
  "php artisan key:generate --force",
  "php artisan migrate --force",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"